import type { LocalQuestion } from "../types";

export const QUESTIONS: LocalQuestion[] = [
  { q: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], answer: 2, category: "Geography" },
  { q: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], answer: 1, category: "Math" },
  { q: "What is the largest planet in our solar system?", options: ["Saturn", "Neptune", "Jupiter", "Uranus"], answer: 2, category: "Science" },
  { q: "Who painted the Mona Lisa?", options: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"], answer: 1, category: "Art" },
  { q: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], answer: 2, category: "Science" },
  { q: "In what year did World War II end?", options: ["1943", "1944", "1945", "1946"], answer: 2, category: "History" },
  { q: "What is the fastest land animal?", options: ["Lion", "Cheetah", "Leopard", "Gazelle"], answer: 1, category: "Nature" },
  { q: "How many bones are in the adult human body?", options: ["196", "206", "216", "226"], answer: 1, category: "Science" },
  { q: "What language has the most native speakers?", options: ["English", "Spanish", "Hindi", "Mandarin Chinese"], answer: 3, category: "Language" },
  { q: "What is the square root of 144?", options: ["11", "12", "13", "14"], answer: 1, category: "Math" },
  { q: "What year was Bitcoin created?", options: ["2007", "2008", "2009", "2010"], answer: 2, category: "Crypto" },
  { q: "Who created Bitcoin?", options: ["Vitalik Buterin", "Satoshi Nakamoto", "Nick Szabo", "Hal Finney"], answer: 1, category: "Crypto" },
  { q: "What does NFT stand for?", options: ["Non-Fungible Token", "New Financial Technology", "Network File Transfer", "Node Format Type"], answer: 0, category: "Crypto" },
  { q: "What is the symbol for Ethereum?", options: ["BTC", "ETH", "SOL", "CELO"], answer: 1, category: "Crypto" },
  { q: "What does DeFi stand for?", options: ["Decentralized Finance", "Digital Finance", "Distributed Finance", "Defined Finance"], answer: 0, category: "Crypto" },
  { q: "What is a smart contract?", options: ["A legal document", "Self-executing code on blockchain", "A type of wallet", "A crypto exchange"], answer: 1, category: "Crypto" },
  { q: "What does 'gas' refer to in Ethereum?", options: ["Fuel for cars", "Transaction fee", "Mining reward", "Block size"], answer: 1, category: "Crypto" },
  { q: "What is GoodDollar's mission?", options: ["DeFi trading", "Universal Basic Income via crypto", "NFT marketplace", "Crypto lending"], answer: 1, category: "Crypto" },
  { q: "What is MiniPay?", options: ["A hardware wallet", "A mobile crypto wallet for Africa", "A DEX", "A stablecoin"], answer: 1, category: "Crypto" },
  { q: "What is the native currency of the Celo network?", options: ["ETH", "BNB", "CELO", "MATIC"], answer: 2, category: "Crypto" },
  { q: "What is the speed of light (approx)?", options: ["299,792 km/s", "199,792 km/s", "399,792 km/s", "499,792 km/s"], answer: 0, category: "Science" },
  { q: "What planet is known as the Red Planet?", options: ["Venus", "Jupiter", "Mars", "Saturn"], answer: 2, category: "Science" },
  { q: "What is H₂O?", options: ["Hydrogen peroxide", "Water", "Oxygen", "Carbon dioxide"], answer: 1, category: "Science" },
  { q: "How many chromosomes do humans have?", options: ["23", "46", "48", "44"], answer: 1, category: "Science" },
  { q: "What force keeps us on the ground?", options: ["Magnetism", "Friction", "Gravity", "Nuclear force"], answer: 2, category: "Science" },
  { q: "Who was the first human to walk on the Moon?", options: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "John Glenn"], answer: 2, category: "History" },
  { q: "In what year did the Berlin Wall fall?", options: ["1987", "1988", "1989", "1990"], answer: 2, category: "History" },
  { q: "Who was the first President of the United States?", options: ["John Adams", "Thomas Jefferson", "George Washington", "Benjamin Franklin"], answer: 2, category: "History" },
  { q: "What year did humans first land on the Moon?", options: ["1967", "1968", "1969", "1970"], answer: 2, category: "History" },
  { q: "Which empire built the Colosseum?", options: ["Greek", "Ottoman", "Roman", "Byzantine"], answer: 2, category: "History" },
  { q: "What is the longest river in the world?", options: ["Amazon", "Mississippi", "Nile", "Yangtze"], answer: 2, category: "Geography" },
  { q: "What is the smallest country in the world?", options: ["Monaco", "Vatican City", "Nauru", "San Marino"], answer: 1, category: "Geography" },
  { q: "On which continent is the Sahara Desert?", options: ["Asia", "South America", "Australia", "Africa"], answer: 3, category: "Geography" },
  { q: "What is the capital of Japan?", options: ["Osaka", "Kyoto", "Tokyo", "Hiroshima"], answer: 2, category: "Geography" },
  { q: "How many continents are on Earth?", options: ["5", "6", "7", "8"], answer: 2, category: "Geography" },
  { q: "What film features the phrase 'To infinity and beyond!'?", options: ["Cars", "Finding Nemo", "Toy Story", "The Lion King"], answer: 2, category: "Pop Culture" },
  { q: "How many strings does a standard guitar have?", options: ["4", "5", "6", "7"], answer: 2, category: "Music" },
  { q: "What sport uses a shuttlecock?", options: ["Tennis", "Badminton", "Squash", "Racquetball"], answer: 1, category: "Sports" },
  { q: "Which company made the first iPhone?", options: ["Samsung", "Apple", "Nokia", "Sony"], answer: 1, category: "Technology" },
  { q: "How many players are on a standard soccer team?", options: ["9", "10", "11", "12"], answer: 2, category: "Sports" },
];
